session_name: mmonitor#mobile
start_directory: ./ # load session relative to config location (project root).
windows:
- window_name: vim
  panes:
    - vim
- window_name: git
  panes:
    - shell_command:
      - git fetch
      - git status
- window_name: server
  panes:
    - ionic serve
